name: Build, deploy Dockerized ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t victorsenishyn/office-control-system:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER }}" | docker login -u victorsenishyn --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push victorsenishyn/office-control-system:${{ github.sha }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OfficeControlSystemAzure'
          slot-name: 'Production'
          images: 'victorsenishyn/office-control-system:${{ github.sha }}'
