name: Build and deploy ASP.Net Core app to Azure Web App - OfficeControlSystemAzure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: myapp:latest

      - name: Upload Docker image artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B5A0D86ACB5E4570A9FD241ABEBD7418 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_512BBB8F6D8944FBA734170BCA33CECE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81B88D92A19A4D32B2625BF820027919 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OfficeControlSystemAzure'
          slot-name: 'Production'
          images: 'myapp:latest'
